name = "quizkk"
main = "main.js"
compatibility_date = "2025-07-24"

[assets]
bucket = "./quizzes"
binding = "ASSETS"

[[kv_namespaces]]
binding = "kv_quiz"
id = "b64b10c45bf3400a8b808adb0fe2b02d"
binding = "kv_quiz"
id = "b64b10c45bf3400a8b808adb0fe2b02d"
